export const SIMPLE_PAIRING_CAPABILITY_FIELD = "simple_pairing" as const;
export const SIMPLE_PAIRING_CAPABILITY_VALUE = true as const;

export const SIMPLE_PAIRING_CAPABILITY_RESPONSE = {
  [SIMPLE_PAIRING_CAPABILITY_FIELD]: SIMPLE_PAIRING_CAPABILITY_VALUE,
} as const;
